### ISSUE TITLE
Changes to namespace scoped children are missed when using a CompositeController with a cluster scoped parent

### ISSUE THREAD

**Issue by jschrantz** [GoogleCloudPlatform/metacontroller#131]
It seems like when you have a CompositeController with a cluster scoped parent and namespace scoped children the objects will be successfully created, but any events on the children are missed and do not cause a sync call.

I created a quick example repo at https://github.com/jschrantz/metacontroller-example showing this behavior.

Here's some highlights from that example showing off the issue:

CompositeController
```
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: cluster-namespaced-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: example.com/v1
    resource: cluster-namespaceds
  childResources:
  - apiVersion: networking.k8s.io/v1
    resource: networkpolicies
    updateStrategy:
      method: InPlace
  hooks:
    sync:
      webhook:
        url: http://cluster-namespaced-controller.cluster-namespaced/sync
```

example.yaml (ClusterNamespaced object)
```
apiVersion: example.com/v1
kind: ClusterNamespaced
metadata:
  name: cluster-namespaced-example
```

Test script
```
echo "Create cluster-namespaced-example ClusterNamespaced object..."
kubectl apply -f example.yaml && sleep 5
echo

echo "Verify the networkpolicy is there..."
kubectl -n cluster-namespaced get networkpolicy cluster-namespaced-example
echo

echo "Delete the networkpolicy..."
kubectl -n cluster-namespaced delete networkpolicy/cluster-namespaced-example && sleep 5
echo

echo "Verify the networkpolicy was recreated..."
kubectl -n cluster-namespaced get networkpolicy cluster-namespaced-example
echo

echo "Delete the ClusterNamespaced object..."
kubectl delete ClusterNamespaced.example.com cluster-namespaced-example
echo
```

Run of the test script
```
$ ./test.sh
Create cluster-namespaced-example ClusterNamespaced object...
clusternamespaced.example.com/cluster-namespaced-example configured

Verify the networkpolicy is there...
NAME                         POD-SELECTOR   AGE
cluster-namespaced-example   <none>         18h

Delete the networkpolicy...
networkpolicy.extensions "cluster-namespaced-example" deleted

Verify the networkpolicy was recreated...
No resources found.
Error from server (NotFound): networkpolicies.extensions "cluster-namespaced-example" not found

Delete the ClusterNamespaced object...
clusternamespaced.example.com "cluster-namespaced-example" deleted
```

Note that this 'test' is failing after removing the networkpolicy and checking whether it was recreated.

The networkpolicy won't regenerate until the cache is flushed or something changes on a non namespace scoped object.

There are two other examples in that repository. A namespace scoped parent creating namespace scoped children which works as you'd expect and a cluster scoped parent creating both cluster and namespace scoped children that is able to detect the cluster scoped child changes, but not the namespace scoped ones.
