### ISSUE TITLE
Running Voyager ingress metacontroller fails, because of need to reconcile internal resources of Voyager

### ISSUE THREAD

**Issue by mikefaraponov** [GoogleCloudPlatform/metacontroller#151]
When running other resources managed by another operator (Voyager) via metacontroller, he tries to reconcile state of internal resources of Voyager (service, etc.).

**Comment by enisoc** [comment]
Sorry, I don't understand. Can you give a code snippet or log entries to show what you're trying to do, and what the resulting behavior is?

**Comment by mikefaraponov** [comment]
So, I has
```yaml
childResources:
    - apiVersion: v1
      resource: pods
    - apiVersion: v1
      resource: persistentvolumeclaims
    - apiVersion: voyager.for.example
      resource: ingress
    - apiVersion: v1
      resource: services
      updateStrategy:
        method: InPlace
```
When I try to utilise ingress, it create additional resources (Voyager Operator creates it) and looks like metacontroller tries to reconcile them. But I expect Voyager resource have to be black box and not expose underling resources to metacontroller
