### ISSUE TITLE
[Feature Request] - User configurable webhook timeout. 

### ISSUE THREAD

**Issue by xocoatzin** [GoogleCloudPlatform/metacontroller#54]
I recently discovered this project and it looks really great!

### Context
I was considering an application for which `metacontroler` would fit perfectly. A concern I have is that as part of my controller, I would need to make a couple REST calls to an external API to resolve certain conditions at run time. I learned from the [source code](https://github.com/GoogleCloudPlatform/metacontroller/blob/d2bcf42f89860448e63a089720b959be4b4686da/hooks/webhook.go#L34) that the `hook` calls have a hard-coded deadline of 10 seconds, which is quite limiting.

Is there a reason for this particular value (10s)? I assume it shouldn't be a big issue to rise this limit or make it user-defined if the hook calls are being called asynchronously under the hood (and assuming the hook handler is replicated). 

Additional question: How would `metacontroler` handle error conditions on the hook (e.g. return status `!200` or timeouts)? Will the call be skipped, retried, etc?

### Request:

Add an option for the webhook configuration similar to:

```yaml
spec:
  hooks:
    sync:
      webhook:
        url: http://hello-controller.hello/sync
        timeoutSeconds: 60               # Timeout in seconds for the webhook 
```
