### ISSUE TITLE
support updating status of resources managed by other controllers

### ISSUE THREAD

**Issue by gurvindersingh** [GoogleCloudPlatform/metacontroller#58]
Thanks @enisoc for your efforts. This makes writing controller much easier :)

I am trying to write a controller to create a load balancer service in external load balancer when a service is created in the cluster with `type: LoadBalancer`. I  also need to create a corresponding `NetworkPolicy`to allow traffic from LB nodes to worker nodes for the given service. Looking from the document `DecoratorController` seems like a close fit (with an issue) as `CompositeController` assumes ownership of parentresource. In my current use case parentresource is `Service.v1`. 

`DecoratorController` creates the desired `NetworkPolicy` object but does not allow me to update the `Status`field of  the service which is target resource as defined below. 

```yaml
apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: lb
spec:
  resources:
  - apiVersion: v1
    resource: services
  attachments:
  - apiVersion: networking.k8s.io/v1
    resource: networkpolicies
  hooks:
    sync:
      webhook:
        url: http://service-per-pod.metacontroller/sync-lb
```

I need to update the `Status` field with info with newly created Loadbalancer IP and hostname, so users can see the IP address they can use to reach their service. I have created an [example](https://gist.github.com/gurvindersingh/3d361c5e0ea35fda98002bf649ea22c3) using jsonnet which in gist show I would like to use.

So wondering is there any plan to add support for this feature in `DecoratorController` or create any other controller which can let me do what I need in this use case.
