### ISSUE TITLE
Document RBAC permissions for Metacontroller

### ISSUE THREAD

**Issue by kalise** [GoogleCloudPlatform/metacontroller#81]
Hello, thanks for sharing this awesome tool!
Is there any reason for running the metacontroller in a dedicated namespace? 
I see these RBAC permissions

```
kind: ClusterRole
metadata:
  name: metacontroller
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
```

Is it possible to run the metacontroller in `kube-system` namespace? Which minimum permissions it needs to work?

Thanks.

**Comment by rlguarino** [comment]
You should be able to give MetaController the minimal set of permissions it needs to do work. The strictest set of things that MetaController needs to access is its CRDs, but it wouldn't be very useful.

Since MetaController manages resources on behalf of its child controllers, MetaController needs rights to manage any of the resources that a child controller manages. So if there's no child controller that needs to list or manage pods then MetaController does not need access to Pods at all.

We could use an [Aggregate role][aggregate-role] for meta controller and it could be standard practice that controller authors would package RBAC Roles that they need.

That could look something like this. We would package the following Aggregate Role with MetaController:

```yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metacontroller
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.k8s.io/aggregate-to-metacontroller: "true"
rules: 
- apiGroups: ["metacontroller.k8s.io"]
  resources: ["compositecontroller", "decoratorcontroller", "controllerrevisions"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
```

Then a controller author would create and distribute the following with their app:

> In this example the controller needs to manage deployments resouces and the parent resources is a custom CRD.
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aggregate-cron-tabs-view
  labels:
    # Add these permissions to the "metacontroller" default role.
    rbac.authorization.k8s.io/aggregate-to-metacontroller: "true"
rules:
- apiGroups: ["example.com"]
  resources: ["bluegreendeployment"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
```

[aggregate-role]: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles
