### ISSUE TITLE
Design pattern to reconcile external resources

### ISSUE THREAD

**Issue by kalise** [GoogleCloudPlatform/metacontroller#83]
> the initial controller patterns we support are focused on use cases where both the inputs and outputs of your controller can be expressed as Kubernetes API objects (either built-in or custom). If you have a concrete use case that involves reconciling external state, we’d appreciate if you file an issue describing it so we can work on defining additional patterns.

Hello, we're trying to use Metacontroller for a custom use case. We want to aggregate multiple Kubernetes clusters (two for production and multiple for development), without going into complexity of the federation feature. The basic idea is to use a tiny Kubernetes control plane as aggregation layer in front of the other clusters. We set an API Server with its own local etcd and a custom CRD resource modelling the cluster we want to manage. Here an example:

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: clusters.example.com
spec:
  scope: Namespaced
  group: example.com
  versions:
    - name: v1alpha2
      served: true
      storage: true      
  names:
    kind: Cluster
    singular: cluster
    plural: clusters
    shortNames:
    - cl
    - cls
  subresources:
    status:
  additionalPrinterColumns:
    - name: address
      type: string
      description: the cluster address, e.g. "35.128.9.208"
      JSONPath: .spec.address
    - name: port
      type: string
      description: the cluster listening port, e.g. 8443
      JSONPath: .spec.port
    - name: secure
      type: boolean
      description: secure communication with the remote cluster, e.g. false, true
      JSONPath: .spec.secure
    - name: admin
      type: string
      description: the administrative state of the cluster, e.g. true, false
      JSONPath: .spec.admin
    - name: state
      type: string
      description: the operational state of the cluster, e.g. "working", "maintenance", "unreachable"
      JSONPath: .status.state
    - name: Age
      type: date
      description: Creation timestamp
      JSONPath: .metadata.creationTimestamp
...
```

Children resources of the cluster CRD are: a Pod running a small agent to pull summary data from the managed cluster and checking the liveness of it, an headless Service specifying where to reach the managed cluster (address and port) and an Ingress required to instruct the ingress controller to proxy requests towards the managed cluster.

We set the Metacontroller and wrote a webhook to reconcile the status of the cluster when it is added/removed/put-in-maintenance by the sys admin. However, we still need how to reconcile the status when it becomes unreachable, because e.g., of the network issues or become unmanageable, because e.g., of token expiring, etc..

These type of events are not under the control of the managing API server and also using Metacontroller polling we cannot intercept them. A possible solution we're exploring is to pass these events from the agent Pod (it's able to intercept them, it's its own job) to the managing API server but we're not sure if possible. Any idea?

Thanks
