### ISSUE TITLE
x509: failed to load system roots and no roots provided

### ISSUE THREAD

**Issue by lionelvillard** [GoogleCloudPlatform/metacontroller#86]
I've created a simple decorator with an external (not a k8s service) webhook. I'm getting the x509 error. 

Potential solution: mount /etc/ssl/certs in metacontroller container.

```
...
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ca-certificates
          readOnly: true
    volumes:
    - name: ca-certificates
       hostPath:
          path: /etc/ssl/certs
```
