### ISSUE TITLE
Double webhook calls with same state, succeeded objects disappearing (CompositeController)

### ISSUE THREAD

**Issue by akaihola** [GoogleCloudPlatform/metacontroller#97]
I'm experimenting with writing a job pipeline controller which delays launching jobs until their specified dependencies have succeeded. I started from [examples/indexedjob](/GoogleCloudPlatform/metacontroller/tree/master/examples/indexedjob) and created [examples/jobtree](/GoogleCloudPlatform/metacontroller/compare/master...akaihola:jobtree-example?expand=1) based on it.

I see a strange behavior where my webhook is sometimes called twice with the same controller status but different observed child pod phases. In some of those cases, a pod which was previously `Running` is first shown as `Succeeded` in the first call, and then completely missing in the second call. I've added an incrementing counter in the controller status, and this reveals the double calls in the log:

- `counter: `**`5`**
  `time: 2018-09-22T19:18:18`
  `phases from previous call: {a: Running, b: Pending, c: Pending}`
  `current pod phases: {a: Running, b: Running, c: Running}`
  `phases combined: {a: Running, b: Running, c: Running}`
  `desired jobs: [a, b, c]`
- `counter: `**`6`**
  `time: 2018-09-22T19:18:25`
  `phases from previous call: {`**`a: Running`**`, b: Running, c: Running}`
  `current pod phases: {`**`a: Succeeded`**`, b: Running, c: Running}`
  `phases combined: {a: Succeeded, b: Running, c: Running}`
  `desired jobs: [b, c]`
- `counter: `**`6`**
  `time: 2018-09-22T19:18:25`
  `phases from previous call: {`**`a: Running`**`, b: Running, c: Running}`
  `current pod phases: {b: Running, c: Running}  `**(pod '`a`' disappeared)**
  `phases combined: {a: Running, b: Running, c: Running}`
  `desired jobs: [a, b, c]`

To make the controller work correctly, I'd have to interpret a dissapeared pod as `Succeeded`. Otherwise it is re-inserted into desired jobs and started again.

I believe I've understood and followed the advice in [Best Practices](https://metacontroller.app/guide/best-practices/) about "Side Effects" and "Status" by not including the desired pods in the controller status returned by the webhook. To me it seems that the second call is not a "hypothetical" proble from Metacontroller – it is acting on the desired state because I'm seeing some jobs run twice.

(Note that in my code base linked to above, I've worked around this issue by recording the phase of a disappearing running pod as `Disappeared` and interpreting is as `Succeeded` when calculating the desired jobs. So running the `my-jobtree.yaml` example will work around this problem by not re-inserting the disappeared job into the list of desired pods.)

I wonder if this behavior of Metacontroller is intentional or if I've misunderstood something as a novice Kubernetes user.

**Comment by mikebryant** [comment]
From https://metacontroller.app/api/compositecontroller/: `Any objects sent as children in the request that you decline to return in your response list will be deleted`

So in the second request, the hook didn't return `a` in the `desired jobs`, therefor metaconroller removed it as requested. As there's been a change in state, it then calls the sync hook again (e.g. so `status` can be updated), at which point the hook sees no job and creates it again.

If you don't want to lose track of the status of the completed Job, you'll need to keep it in your desired state, which will mean metacontroller won't delete it.

**Comment by akaihola** [comment]
Thanks @mikebryant for your explanation.

There's still one thing I don't understand: If you look carefully at my example, both the second and the third request receive the state set by the first request. In other words, the state set by the second request is lost.

From the viewpoint of the third request, `a: Succeeded` *never happened*. The previous state was `a: Running` in the first request.

I created the incrementing counter to make sure this really is the case. The handler gets the counter in the parent status, increments it, and returns it as part of the status.

So why doesn't the third request receive `{counter:6, phases: {a: Succeeded, b: Running, c: Running}}` as set by the second request? Why does it receive `{counter:5, phases: {a: Running, b: Running, c: Running}}` as set by the *first* request instead?

**Comment by mikebryant** [comment]
I'm afraid I don't know the project well enough to answer that, hopefully someone else can chime in :)

**Comment by danisla** [comment]
Looking your [CRD spec](https://github.com/GoogleCloudPlatform/metacontroller/commit/389a1355e494269e51230877e576000d42fd3a39#diff-c8180cdc9029636e7bd525b341560b7aR6), the `dependencies` is a map of strings. In JSON, these have no order to them so during serialization, the order could get shuffled. 

Metacontroller is setting the annotation `metacontroller.k8s.io/last-applied-configuration` on your parent object with the JSON serialized content, so this has to be stable across sync requests, otherwise you could enter a hot loop where it's constantly thinking the parent resource is changing and attempting to reconcile the change. I saw this in one of my controllers and mentioned it in [#76](https://github.com/GoogleCloudPlatform/metacontroller/issues/76#issuecomment-423654218)

Have a look at the metacontroller logs when running it with the `-v=5` arg. This will show you more info about what the metacontroller is seeing and might help confirm the hot-loop scenario.

If this is the issue, try converting the `dependencies` field to an ordered list, to see if that helps.

**Comment by akaihola** [comment]
@danisla, I tried out your suggestion. I replaced both `spec.dependencies` in the CRD spec and the `status.phases` in the webhook return value with nested lists which only contain string values.

Unfortunately this had no effect on the symptom. I'm still getting double invocations of the webhook, where the second invocation doesn't carry state from the first one, but from a preceding call instead.

Additionally, this makes both the [new CRD spec](/GoogleCloudPlatform/metacontroller/compare/master...akaihola:jobtree-example-no-string-maps?expand=1#diff-c8180cdc9029636e7bd525b341560b7a) and the [webhook code](/GoogleCloudPlatform/metacontroller/compare/master...akaihola:jobtree-example-no-string-maps?expand=1#diff-0ccdc3600439712dbec93f833d2bd802) more difficult to reason about. I would think that it's worth the effort to make sure metacontroller can correctly compare maps of strings as well.

@mikebryant's suggestion to keep succeeded pods in the list of desired pods actually solves the issue, but doesn't actually get rid of the double invocations. They just aren't fatal any more in that setup.

Here's an example of the double invocations when using nested lists instead of maps of strings:
```yaml
- status.counter: 10
  time: 2018-09-24T09:13:51
  got status.phases: [(background, Running), (a, Running), (b, Running), (c, Running)]
  current pod phases: {a: Running, b: Succeeded, background: Running, c: Running}
  new status.phases: [(background, Running), (a, Running), (b, Succeeded), (c, Running)]
  desired jobs: [background, a, c, d]
- status.counter: 11
  time: 2018-09-24T09:13:56
  got status.phases: [(background, Running), (a, Running), (b, Succeeded), (c, Running)]
  current pod phases: {a: Succeeded, background: Running, c: Succeeded, d: Pending}
  new status.phases: [(background, Running), (a, Succeeded), (b, Succeeded), (c, Succeeded), (d, Pending)]
  desired jobs: [background, d]
- status.counter: 11
  time: 2018-09-24T09:14:05
  WARNING 31: Job a was Running but disappeared. Assuming it to have succeeded.
  WARNING 31: Job c was Running but disappeared. Assuming it to have succeeded.
  got status.phases: [(background, Running), (a, Running), (b, Succeeded), (c, Running)]
  current pod phases: {background: Running, d: Pending}
  new status.phases: [(background, Running), (a, Disappeared), (b, Succeeded), (c, Disappeared), (d, Pending)]
  desired jobs: [background, d]
```
Notice how `got status.phases` in the last invocation is the one returned from the first call (see `new status.phases`) instead of the second call.
